spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  sql:
    init:
      mode: always
#      encoding: UTF-8

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
#        generate_statistics: true
#        use_sql_comments: true
#        format_sql: true
##        show SQL statements only if needed!
#        show_sql: true
#        type: trace

  #Cloudinary Properties
cloudinary:
  api-key: 579953547744991
  api-secret: ${CLOUDINARY_API_SECRET}
  cloud-name: trippictures

  #Loggers
logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: Trace
#    sql: debug

server:
  port=${PORT:8080}